# Generated by Django 5.2.4 on 2025-08-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='event_images/'),
        ),
    ]
