# Generated by Django 5.2.4 on 2025-08-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('CON', 'Conference'), ('WRK', 'Workshop'), ('SEM', 'Seminar'), ('MTP', 'Meetup')], max_length=5),
        ),
    ]
