# Generated by Django 5.2.4 on 2025-08-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_category_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
    ]
