# nixpacks.toml

[phases.build]
cmds = [
  "npm install",
  "python manage.py tailwind install",
  "python manage.py tailwind build",
  "python manage.py collectstatic --noinput"
]

[phases.deploy]
start = "gunicorn eventura.wsgi"
