# nixpacks.toml

[phases.setup]
nixPkgs = ["python3.11", "postgresql"]

[phases.install]
cmds = ["pip install --upgrade pip && pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn eventura.wsgi --workers 4 --threads 4"
