
services:
  - type: web
    name: eventura
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn eventura.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eventura-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
